version: "3.8"

services:

  configserver:
    image: manmohankumar/bankconfigserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - securebank-network

    eurekaserver:
      image: manmohankumar/eurekabankserver:latest
      mem_limit: 700m
      ports:
        - "8070:8070"
      networks:
        - securebank-network
      depends_on:
        - configserver
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071

  accounts:
    image: manmohankumar/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - securebank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max-attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: eurekaserver:http://eurekaserver:8070/eureka
    
  loans:
    image: manmohankumar/loans:v2.0
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - securebank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max-attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: eurekaserver:http://eurekaserver:8070/eureka
    
  cards:
    image: manmohankumar/cards:v2.0
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - securebank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max-attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: eurekaserver:http://eurekaserver:8070/eureka
    
networks:
  securebank-network: